// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzltyppqgqslghporvme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bHR5cHBxZ3FzbGdocG9ydm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTUwNDksImV4cCI6MjA3NDYzMTA0OX0.7lEWEnKvr95PtNrGGj8nPOYkrxWZCYZvC8_xr2em6B4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});